apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/baremetal/deploy.yaml
- configmap.yml
- fastapi_deployment.yml
- fastapi_service.yml
- frontend_deployment.yml
- frontend_service.yml
- ingress.yml
- monitoring/prometheus-configmap.yml
- monitoring/prometheus-rbac.yml
- monitoring/prometheus-deployment.yml
- monitoring/prometheus-service.yml
- monitoring/grafana-deployment.yml
- monitoring/grafana-service.yml

patches:
- path: ingress_nginx.yml
images:
- name: registry.gitlab.com/shotorouu/devops-qr-code/api
  newTag: 9a3abae2140f8181e4d2ba1f4ea8c463b6c53495
- name: registry.gitlab.com/shotorouu/devops-qr-code/front
  newTag: 9a3abae2140f8181e4d2ba1f4ea8c463b6c53495
